goal/mylb/config/routes.rb
Rails.application.routes.draw do
  resources :user_scores
  resources :leaderboards
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

goal/mylb/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

goal/mylb/app/models/leaderboard.rb
class Leaderboard < ApplicationRecord
end

goal/mylb/app/models/user_score.rb
class UserScore < ApplicationRecord
  belongs_to :leaderboard
end

goal/mylb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

goal/mylb/app/controllers/leaderboards_controller.rb
class LeaderboardsController < ApplicationController
  before_action :set_leaderboard, only: [:show, :edit, :update, :destroy]

  # GET /leaderboards
  # GET /leaderboards.json
  def index
    @leaderboards = Leaderboard.all
  end

  # GET /leaderboards/1
  # GET /leaderboards/1.json
  def show
  end

  # GET /leaderboards/new
  def new
    @leaderboard = Leaderboard.new
  end

  # GET /leaderboards/1/edit
  def edit
  end

  # POST /leaderboards
  # POST /leaderboards.json
  def create
    @leaderboard = Leaderboard.new(leaderboard_params)

    respond_to do |format|
      if @leaderboard.save
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully created.' }
        format.json { render :show, status: :created, location: @leaderboard }
      else
        format.html { render :new }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leaderboards/1
  # PATCH/PUT /leaderboards/1.json
  def update
    respond_to do |format|
      if @leaderboard.update(leaderboard_params)
        format.html { redirect_to @leaderboard, notice: 'Leaderboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @leaderboard }
      else
        format.html { render :edit }
        format.json { render json: @leaderboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leaderboards/1
  # DELETE /leaderboards/1.json
  def destroy
    @leaderboard.destroy
    respond_to do |format|
      format.html { redirect_to leaderboards_url, notice: 'Leaderboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leaderboard
      @leaderboard = Leaderboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leaderboard_params
      params.require(:leaderboard).permit(:name, :company_name)
    end
end

goal/mylb/app/controllers/user_scores_controller.rb
class UserScoresController < ApplicationController
  before_action :set_user_score, only: [:show, :edit, :update, :destroy]

  # GET /user_scores
  # GET /user_scores.json
  def index
    @user_scores = UserScore.all
  end

  # GET /user_scores/1
  # GET /user_scores/1.json
  def show
  end

  # GET /user_scores/new
  def new
    @user_score = UserScore.new
  end

  # GET /user_scores/1/edit
  def edit
  end

  # POST /user_scores
  # POST /user_scores.json
  def create
    @user_score = UserScore.new(user_score_params)

    respond_to do |format|
      if @user_score.save
        format.html { redirect_to @user_score, notice: 'User score was successfully created.' }
        format.json { render :show, status: :created, location: @user_score }
      else
        format.html { render :new }
        format.json { render json: @user_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_scores/1
  # PATCH/PUT /user_scores/1.json
  def update
    respond_to do |format|
      if @user_score.update(user_score_params)
        format.html { redirect_to @user_score, notice: 'User score was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_score }
      else
        format.html { render :edit }
        format.json { render json: @user_score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_scores/1
  # DELETE /user_scores/1.json
  def destroy
    @user_score.destroy
    respond_to do |format|
      format.html { redirect_to user_scores_url, notice: 'User score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_score
      @user_score = UserScore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_score_params
      params.require(:user_score).permit(:user_name, :points, :leaderboard_id)
    end
end

goal/mylb/app/helpers/application_helper.rb
module ApplicationHelper
end

goal/mylb/app/helpers/leaderboards_helper.rb
module LeaderboardsHelper
end

goal/mylb/app/helpers/user_scores_helper.rb
module UserScoresHelper
end

goal/mylb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mylb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

goal/mylb/app/views/leaderboards/_form.html.erb
<%= form_with(model: leaderboard, local: true) do |form| %>
  <% if leaderboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leaderboard.errors.count, "error") %> prohibited this leaderboard from being saved:</h2>

      <ul>
      <% leaderboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :company_name %>
    <%= form.text_field :company_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

goal/mylb/app/views/leaderboards/edit.html.erb
<h1>Editing Leaderboard</h1>

<%= render 'form', leaderboard: @leaderboard %>

<%= link_to 'Show', @leaderboard %> |
<%= link_to 'Back', leaderboards_path %>

goal/mylb/app/views/leaderboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Leaderboards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leaderboards.each do |leaderboard| %>
      <tr>
        <td><%= leaderboard.name %></td>
        <td><%= leaderboard.company_name %></td>
        <td><%= link_to 'Show', leaderboard %></td>
        <td><%= link_to 'Edit', edit_leaderboard_path(leaderboard) %></td>
        <td><%= link_to 'Destroy', leaderboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Leaderboard', new_leaderboard_path %>

goal/mylb/app/views/leaderboards/new.html.erb
<h1>New Leaderboard</h1>

<%= render 'form', leaderboard: @leaderboard %>

<%= link_to 'Back', leaderboards_path %>

goal/mylb/app/views/leaderboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @leaderboard.name %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @leaderboard.company_name %>
</p>

<%= link_to 'Edit', edit_leaderboard_path(@leaderboard) %> |
<%= link_to 'Back', leaderboards_path %>

goal/mylb/app/views/user_scores/_form.html.erb
<%= form_with(model: user_score, local: true) do |form| %>
  <% if user_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_score.errors.count, "error") %> prohibited this user_score from being saved:</h2>

      <ul>
      <% user_score.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name %>
  </div>

  <div class="field">
    <%= form.label :points %>
    <%= form.number_field :points %>
  </div>

  <div class="field">
    <%= form.label :leaderboard_id %>
    <%= form.text_field :leaderboard_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

goal/mylb/app/views/user_scores/edit.html.erb
<h1>Editing User Score</h1>

<%= render 'form', user_score: @user_score %>

<%= link_to 'Show', @user_score %> |
<%= link_to 'Back', user_scores_path %>

goal/mylb/app/views/user_scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Scores</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Points</th>
      <th>Leaderboard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_scores.each do |user_score| %>
      <tr>
        <td><%= user_score.user_name %></td>
        <td><%= user_score.points %></td>
        <td><%= user_score.leaderboard %></td>
        <td><%= link_to 'Show', user_score %></td>
        <td><%= link_to 'Edit', edit_user_score_path(user_score) %></td>
        <td><%= link_to 'Destroy', user_score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Score', new_user_score_path %>

goal/mylb/app/views/user_scores/new.html.erb
<h1>New User Score</h1>

<%= render 'form', user_score: @user_score %>

<%= link_to 'Back', user_scores_path %>

goal/mylb/app/views/user_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @user_score.user_name %>
</p>

<p>
  <strong>Points:</strong>
  <%= @user_score.points %>
</p>

<p>
  <strong>Leaderboard:</strong>
  <%= @user_score.leaderboard %>
</p>

<%= link_to 'Edit', edit_user_score_path(@user_score) %> |
<%= link_to 'Back', user_scores_path %>